apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: rain-detector
  name: rain-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rain-detector
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/weather-station-monitoring-default: "true"
        io.kompose.service: rain-detector
    spec:
      containers:
        - image: rain-detector-image:latest
          name: rain-detector
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
          resources: {}
      restartPolicy: Always
status: {}
